package GUI;
import classes.calendarconfigs;
import classes.student;
import classes.genero;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;



public class New_student extends javax.swing.JFrame {

    /**
     * Creates new form New_note
     */
    calendarconfigs calendarconfigs1 = new calendarconfigs();
    
    student student1;
    ArrayList<student> list = new ArrayList<>();
   
    public New_student() {
        initComponents();
        dates();
    }
    
    public New_student(ArrayList<student> list) 
    {
        initComponents();
        dates();
        this.list = list;
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        done_btn = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        last_name_input = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        ID_input = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        GPA_input = new javax.swing.JTextField();
        Clear_btn = new javax.swing.JButton();
        javax.swing.JLabel age_label = new javax.swing.JLabel();
        age_input = new javax.swing.JTextField();
        cmbbox_month = new javax.swing.JComboBox<>();
        cmbbox_day = new javax.swing.JComboBox<>();
        cmbbox_year = new javax.swing.JComboBox<>();
        javax.swing.JLabel genre_label = new javax.swing.JLabel();
        cmbbox_genre = new javax.swing.JComboBox();
        this_a_month = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New note");
        setLocation(new java.awt.Point(750, 400));

        done_btn.setText("Done");
        done_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel2.setText("Last name");

        jLabel3.setText("ID");

        jLabel4.setText("GPA");

        Clear_btn.setText("Clear");
        Clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btnActionPerformed(evt);
            }
        });

        age_label.setText("Age");

        cmbbox_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbox_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbox_monthActionPerformed(evt);
            }
        });

        cmbbox_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbox_day.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbox_dayItemStateChanged(evt);
            }
        });

        cmbbox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbox_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbox_yearActionPerformed(evt);
            }
        });

        genre_label.setText("Genre");

        cmbbox_genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer", "Otro" }));
        cmbbox_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbox_genreActionPerformed(evt);
            }
        });

        this_a_month.setText("Mes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(done_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clear_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(age_label)
                            .addComponent(genre_label))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbbox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(this_a_month, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbbox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(cmbbox_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_input)
                                .addComponent(last_name_input)
                                .addComponent(ID_input)
                                .addComponent(GPA_input, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                            .addComponent(cmbbox_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_input, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(last_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ID_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GPA_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age_label)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbbox_day, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbbox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbbox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this_a_month, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(age_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_label)
                    .addComponent(cmbbox_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(done_btn)
                    .addComponent(Clear_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void done_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_btnActionPerformed
        // TODO add your handling code here:
        
        
        int comfirm1 = JOptionPane.showConfirmDialog(null,  "Seguro que has terminado?", "", JOptionPane.YES_NO_OPTION);
           if (comfirm1 == JOptionPane.NO_OPTION)
           {
              
           }
           if (comfirm1 == JOptionPane.YES_OPTION)
           {
              done yay = new done(this);
              yay.show();
              int age1 = this.calculate_age();
              this.addtolist();
       
           }
           
        
         /*
        comfirmation comfirm = new comfirmation(this);
        comfirm.setVisible(true);
        comfirm.show();
        */
        
    }//GEN-LAST:event_done_btnActionPerformed
 
    
    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void Clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btnActionPerformed
        this.name_input.setText("");
        this.GPA_input.setText("");
        this.last_name_input.setText("");
        this.ID_input.setText("");
        this.age_input.setText("");
        this.cmbbox_day.setSelectedIndex(0);
        this.cmbbox_month.setSelectedIndex(0);
        this.cmbbox_year.setSelectedIndex(0);
        this.cmbbox_genre.setSelectedIndex(0);
    }//GEN-LAST:event_Clear_btnActionPerformed

    private void cmbbox_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbox_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbox_genreActionPerformed

    private void dates() 
    {
        this.cmbbox_year.setModel(calendarconfigs1.showYear());
        this.cmbbox_month.setModel(calendarconfigs1.showMonth());
        this.cmbbox_day.setModel(calendarconfigs1.showday(Integer.parseInt(cmbbox_month.getSelectedItem().toString()),Integer.parseInt(cmbbox_year.getSelectedItem().toString())));
    }
    
    private void cmbbox_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbox_monthActionPerformed
        this.cmbbox_day.setModel(calendarconfigs1.showday(Integer.parseInt(cmbbox_month.getSelectedItem().toString()),Integer.parseInt(cmbbox_year.getSelectedItem().toString())));
    }//GEN-LAST:event_cmbbox_monthActionPerformed

    private void cmbbox_dayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbox_dayItemStateChanged
      //  this.cmbbox_day.setModel(calendarconfigs1.showday(Integer.parseInt(cmbbox_month.getSelectedItem().toString()),Integer.parseInt(cmbbox_year.getSelectedItem().toString())));
    }//GEN-LAST:event_cmbbox_dayItemStateChanged

    private void cmbbox_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbox_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbox_yearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_student().setVisible(true);
            }
        });
    }
    
    private int calculate_age(){
        int year_of_birth = Integer.parseInt(cmbbox_year.getSelectedItem().toString());
        int current_year = LocalDate.now().getYear();
        int age;
        age = current_year - year_of_birth;
        
        return age;
    }
    
     private void addtolist()
    {
        student1 = new student();
        student1.setName(name_input.getText());
        student1.setLast_name(last_name_input.getText());
        student1.setID(ID_input.getText());
        student1.setGpa(parseFloat(GPA_input.getText()));
        student1.setEdad(this.calculate_age());
        student1.setBirthday(parseInt(cmbbox_day.getSelectedItem().toString()));
        student1.setBirthmonth(parseInt(cmbbox_month.getSelectedItem().toString()));
        student1.setBirthyear(parseInt(cmbbox_year.getSelectedItem().toString()));
        
        genero gen = genero.Hombre;
        
        if (cmbbox_genre.getSelectedIndex() == 0)
           {
          gen = genero.Hombre;
        }
        
        list.add(student1);

    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_btn;
    private javax.swing.JTextField GPA_input;
    private javax.swing.JTextField ID_input;
    private javax.swing.JTextField age_input;
    private javax.swing.JComboBox<String> cmbbox_day;
    private javax.swing.JComboBox cmbbox_genre;
    private javax.swing.JComboBox<String> cmbbox_month;
    private javax.swing.JComboBox<String> cmbbox_year;
    private javax.swing.JButton done_btn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField last_name_input;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel this_a_month;
    // End of variables declaration//GEN-END:variables
}